Repository AY2324S1-CS2103T-T17-4/tp, pull requests merged in 2023-11, with the labels that each got.

#145 Update UG
  docs/UserGuide.md
Labels: documentation

#160 Add back to table of contents after every section
  docs/UserGuide.md
Labels: documentation

#226 Fix bug for minimum height and width
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/resources/view/MainWindow.fxml
Labels: bug

#227 Fix bug to reduce image size for course list panel and tag list panel
  docs/UserGuide.md
Labels: bug

#224 Bug fix for UG and Telehandle error message
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Telehandle.java
Labels: bug, documentation

#232 Include Appendix C: Planned enhancements
  docs/DeveloperGuide.md
Labels: documentation

#241 Update PPP
  docs/team/joel-foo.md
Labels: documentation

#250 Fix sort name - updated
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/team/chewjh1234.md
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/sorter/PersonCourseSizeAscendingSorter.java
  src/main/java/seedu/address/model/person/sorter/PersonCourseSizeDescendingSorter.java
  src/main/java/seedu/address/model/person/sorter/PersonNameAscendingSorter.java
  src/main/java/seedu/address/model/person/sorter/PersonNameDescendingSorter.java
  src/main/java/seedu/address/model/person/sorter/PersonTagSorter.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/sorter/PersonNameAscendingSorterTest.java
  src/test/java/seedu/address/model/person/sorter/PersonNameDescendingSorterTest.java
Labels: bug

#252 Update DG - Add manual testing
  docs/DeveloperGuide.md
  docs/team/chewjh1234.md
Labels: documentation

#254 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FeedbackSequenceDiagram.puml
  docs/diagrams/ThemeActivityDiagram.puml
  docs/diagrams/ThemeSequenceDiagram.puml
  docs/images/AfterAddCommand.png
  docs/images/AfterSortName.png
  docs/images/AfterSortNameDescending.png
  docs/images/AfterSortTags.png
  docs/images/BeforeAddCommand.png
  docs/images/BeforeSortName.png
  docs/images/BeforeSortNameDescending.png
  docs/images/BeforeSortTags.png
  docs/images/BeforeSorting.png
  docs/images/BeforeSortingAscending.png
  docs/images/Clear.png
  docs/images/ClearCoursesAfter.png
  docs/images/ClearCoursesBefore.png
  docs/images/FeedbackSequenceDiagram.png
  docs/images/FindCourseCS2103TMA1521.png
  docs/images/Findcourse.png
  docs/images/FindcourseCS2100MA1521.png
  docs/images/LabelledUI.png
  docs/images/ListFeature.png
  docs/images/SortCourse.png
  docs/images/SortCourseAscending.png
  docs/images/ThemeActivityDiagram.png
  docs/images/ThemeSequenceDiagram.png
  docs/images/Ui.png
  docs/images/deleteFeature.png
  docs/images/editFeatureAfter.png
  docs/images/editFeatureBefore.png
  docs/images/themeMessage.png
Labels: documentation

#255 Update course list with latest courses
  src/main/java/seedu/address/model/util/CourseUtil.java
Labels: bug

#271 Update DG - Add Course Feature
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindStudentSequenceDiagram.puml
  docs/diagrams/FindcourseSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ThemeActivityDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/FindStudentSequenceDiagram.png
  docs/images/FindcourseSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ThemeActivityDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
Labels: documentation

#274 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/FindcourseActivityDiagram.puml
  docs/diagrams/FindstudentActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PanelClassDiagram.puml
  docs/diagrams/ThemeActivityDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/images/FindcourseActivityDiagram.png
  docs/images/FindstudentActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PanelClassDiagram.png
Labels: documentation

#280 Update DG for use cases and future enhancement
  docs/DeveloperGuide.md
Labels: documentation
