Repository AY2324S1-CS2103T-T17-4/tp, pull requests merged in 2023-10, with the labels that each got.

#95 Changed link for HelpCommand to directly link it with NUSCoursemates
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Low

#96 Bug fix for course validation
  data/JSONModuleList.json
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/course/CourseList.java
  src/main/java/seedu/address/storage/JsonCourseParser.java
  src/test/java/seedu/address/model/course/CourseListTest.java
  src/test/java/seedu/address/storage/JsonCourseParserTest.java
Labels: bug

#105 Bug fixes for UI
  src/main/java/seedu/address/ui/TagListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
Labels: bug

#126 Update DG
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/Logo.jpg
  docs/images/ModelClassDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/index.md
Labels: documentation

#130 Update DG for Sort
  docs/DeveloperGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: documentation

#131 Updates to DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FeedbackActivityDiagram.puml
  docs/diagrams/FeedbackSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/TelehandleActivityDiagram.puml
  docs/diagrams/TelehandleSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/FeedbackActivityDiagram.png
  docs/images/FeedbackSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/TelehandleActivityDiagram.png
  docs/images/TelehandleSequenceDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/model/person/Telehandle.java
Labels: documentation

#132 Update UG to include icons information and update the images of some
  docs/UserGuide.md
  docs/images/ListFeature.png
  docs/images/deleteFeature.png
  docs/images/deleteStudent.png
  docs/images/editFeatureAfter.png
  docs/images/editFeatureBefore.png
  docs/images/editStudent.png
  docs/images/list.png
Labels: documentation

#137 Bug Fix in FeedbackWindow and HelpWindow
  src/main/java/seedu/address/ui/FeedbackWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/FeedbackWindow.fxml
  src/main/resources/view/FeedbackWindowDark.css
  src/main/resources/view/FeedbackWindowLight.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/HelpWindowDark.css
  src/main/resources/view/HelpWindowLight.css
Labels: bug
